routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
    [
        'prefix'     => 'admin',
        'middleware' => 'check_admin',
    ],
    static function () {
        Route::resource('categories', 'Admin\CategoryController');
        Route::resource('transports', 'Admin\TransportationController');
        Route::resource('adverts', 'Admin\AdvertController');
        Route::resource('faqs', 'Admin\FaqController');
        Route::resource('advert-comments', 'Admin\AdvertCommentController');
        Route::resource('users', 'Admin\UserController');
        Route::resource('static-contents', 'Admin\StaticContentController');
        Route::resource('prices', 'Admin\PriceController');

        Route::post('upload-image', 'Admin\UploadHelperController@upload')->name('upload-image');
        Route::post('delete-image', 'Admin\UploadHelperController@delete')->name('delete-image');
        Route::post('level-1', 'Admin\DataHelperController@options')->name('options');
    }
);


Route::post('/login', 'Common\LoginController@login')->name('login');
Route::get('/admin', 'Common\LoginController@index')->name('index');

//Route::get('/data', 'Common\LoginController@getData');

app/Models/Category.php
<?php

/**
 * Created by Reliese Model.
 * Date: Mon, 25 Feb 2019 12:35:16 +0000.
 */

namespace App\Models;

use Kalnoy\Nestedset\NodeTrait;
use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Category
 *
 * @property int $id
 * @property int $parent_id
 * @property string $name
 * @property string $description
 * @property string $image
 * @property int $status
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @package App\Models
 */
class Category extends Eloquent
{

    use NodeTrait;

    protected $casts = [
        'parent_id' => 'int',
        'status'    => 'int',
        '_lft'      => 'int',
        '_rgt'      => 'int',
    ];

    protected $fillable = [
        'parent_id',
        'name',
        'description',
        'image',
        'status',
        '_lft',
        '_rgt'
    ];


    public function adverts()
    {
        return $this->hasMany(Advert::class)->with('priceVariants', 'images');
    }

    public function scopeParents($query, $parent_id)
    {
        return $query->where('parent_id', $parent_id);
    }

    public function scopeRoots($query)
    {
        return $query->whereNull('parent_id');
    }


}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Support\Str;

class CategoryController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index()
    {

        $categories = app(Category::class)
            ->with('ancestors')
            ->orderBy('parent_id')
            ->get();

        return view('admin.category.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $root_categories = app(Category::class)
            ->roots()
            ->get();


        return view('admin.category.create', compact('root_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\CategoryRequest $request
     * @return void
     */
    public function store(CategoryRequest $request)
    {

        //Get file
        $file = $request->file('image');

        //Rename file
        $name = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

        //Save file
        \Storage::putFileAs('categories', $request->file('image'), $name);

        //Get path of new file
        $path = \Storage::path('categories/' . $name);

        $img = \Image::make($path);

        //Crop center resize
        $img->fit(600);

        //Saveimage
        $img->save($path);

        $data = $request->all();

        $data['image'] = $name;

        $parent = app(Category::class)->find($request->parent_id);

        if ($parent) {
            app(Category::class)->create($data, $parent);
        } else {
            app(Category::class)->create($data);
        }


        return redirect(config('app.url') . '/admin/categories')->with('success', true);

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    /*public function edit($id)
    {
        $category_response        = $this->api('categories/' . $id);
        $parent_category_response = $this->api('parent-categories');
        $category                 = json_decode($category_response->getContent())->data;
        $parent_categories        = json_decode($parent_category_response->getContent());

        return view('admin.category.edit', compact('category', 'parent_categories'));
    }*/

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\CategoryRequest $request
     * @param int $id
     * @return void
     */
    /*public function update(CategoryRequest $request, $id)
    {

        if ($request->hasFile('image')) {

            //Get file
            $file = $request->file('image');

            //Rename file
            $name = Str::slug($request->name) . '-' . time() . '.' . $file->getClientOriginalExtension();

            //Save file
            \Storage::putFileAs('categories', $request->file('image'), $name);

            //Get path of new file
            $path = \Storage::path('categories/' . $name);

            $img = \Image::make($path);

            //Crop center resize
            $img->fit(600);

            //Saveimage
            $img->save($path);

            $data = $request->all();

            $data['image'] = $name;

            $category = app(Category::class)->create($data);

        } else {
            $category = app(Category::class)->create($request->except('image'));
        }


        //$data = json_decode($res->getContent());

        //if ($data->status) {
        //    return redirect(config('app.url') . '/admin/categories')->with('success', true);
        //}
    }*/

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $res = $this->api('categories/' . $id, 'DELETE');

        $data = json_decode($res->getContent());

        if ($data->status) {
            return redirect(config('app.url') . '/admin/categories')->with('success', true);
        }
    }
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use App\Models\Category;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     *
     */
    public function index()//: JsonResponse
    {
        $categories = app(Category::class)
            //->with('ancestors')
            ->withCount('children')
            ->where('status', 1)
            ->orderBy('parent_id')
            ->get();

        return CategoryResource::collection($categories->toTree());
    }

    /**
     * Show Category
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id): JsonResponse
    {
        try {
            $data = app(Category::class)->findOrFail($id);
        } catch (ModelNotFoundException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success', 'data' => $data]);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request): JsonResponse
    {
        try {
            app(Category::class)
                ->create($request->except(['image']) + ['image' => $request->image]);
        } catch (QueryException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success'], 201);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $data       = app(Category::class)->findOrFail($id);
            $image_name = $request->image;
            $data->update($request->except(['image']) + ['image' => $image_name]);
        } catch (QueryException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        } catch (ModelNotFoundException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy($id): JsonResponse
    {
        try {
            $data = app(Category::class)->findorFail($id);
            $data->delete();
        } catch (ModelNotFoundException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success']);
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.layout-without-navbar-flex')
@section('content')

    <div class="container-fluid flex-grow-1 container-p-y">

        <h4 class="font-weight-bold py-3 mb-4">
            Yeni Kategori
        </h4>

        <div class="card mb-4">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data" action="{{route('categories.store',[],false)}}">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label class="form-label">Ana Kategori</label>
                            <select id="parent"
                                    class="form-control">
                                <option value="0">Yok</option>
                                @foreach($root_categories as $rc)
                                    <option value="{{$rc->id}}">{{$rc->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-4">
                            <div id="level1-div" class="form-group">
                                <label class="form-label">1. Alt Kategori</label>
                                <select id="level1" class="form-control">
                                    <option value="0">Yok</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div id="level2-div" class="form-group">
                                <label class="form-label">2. Alt Kategori</label>
                                <select id="level2" class="form-control">
                                    <option value="0">Yok</option>
                                </select>
                            </div>
                        </div>
                        <input type="hidden" id="parent_id" name="parent_id" value="0">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Adı</label>
                        <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                               name="name">
                        @if ($errors->has('name'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="form-label">Açıklama</label>
                        <input type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                               name="description">
                        @if ($errors->has('description'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="form-label">Görsel</label>
                        <input type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}"
                               name="image">
                        @if ($errors->has('image'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label class="form-label">Durum</label>
                        <select class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}" name="status">
                            <option value="1">Aktif</option>
                            <option value="0">Pasif</option>
                        </select>
                        @if ($errors->has('status'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('status') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="row pull-right">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- / Content -->
@endsection
@section('scripts')
    <script>
        $(function () {

            const token = '{{csrf_token()}}';

            $('#level1-div').hide();
            $('#level2-div').hide();

            $('#parent').on('change', function () {
                let val = $(this).val();
                if (parseInt(val) !== 0) {
                    $.post('{{route('options',[],false)}}', {_token: token, pid: val}, function (res) {
                        $('#level1').children('option:not(:first)').remove();
                        $('#level1').append(res);
                        $('#level1-div').show();
                    });
                } else {
                    $('#level1').children('option:not(:first)').remove();
                    $('#level2').children('option:not(:first)').remove();
                    $('#level1-div').hide();
                    $('#level2-div').hide();
                }

                parent_selector(val);
            });
            $('#level1').on('change', function () {
                let val = $(this).val();
                if (parseInt(val) !== 0) {
                    $.post('{{route('options',[],false)}}', {_token: token, pid: val}, function (res) {
                        $('#level2').children('option:not(:first)').remove();
                        $('#level2').append(res);
                        $('#level2-div').show();
                    });
                } else {
                    $('#level2').children('option:not(:first)').remove();
                    $('#level2-div').hide();
                }

                parseInt(val) === 0
                    ?
                    parent_selector($('#parent').val())
                    :
                    parent_selector(val);

            });

            $('#level2').on('change', function () {

                let val = $(this).val();

                parseInt(val) === 0
                    ?
                    parent_selector($('#level1').val())
                    :
                    parent_selector(val);

            });
        });

        function parent_selector(id) {
            $('#parent_id').val(id);
        }
    </script>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.layout-without-navbar-flex')
@section('content')

    <div class="container-fluid flex-grow-1 container-p-y">

        <h4 class="font-weight-bold py-3 mb-4">
            Kategori Güncelle
        </h4>

        <div class="card mb-4">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data"
                      action="{{route('categories.update',['id'=>$category->id],false)}}">
                    {{ method_field('PUT') }}
                    @csrf
                    <div class="form-group">
                        <label class="form-label">Ana Kategori</label>
                        <select class="form-control{{ $errors->has('parent_id') ? ' is-invalid' : '' }}" name="parent_id">
                            <option value="0">Yok</option>
                            @foreach($parent_categories as $pc)
                                <option value="{{$pc->id}}"
                                        @if($pc->id === $category->parent_id) selected @endif>{{$pc->name}}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('parent_id'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('parent_id') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="form-label">Adı</label>
                        <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{$category->name}}">
                        @if ($errors->has('name'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="form-label">Açıklama</label>
                        <input type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{$category->description}}">
                        @if ($errors->has('description'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label class="form-label">Görsel</label>
                        <br>
                        <img src="/storage/categories/{{$category->image}}" style="width: 300px">
                        <input type="file" name="image" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}">
                        @if ($errors->has('image'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>

                    <div class="form-group">
                        <label class="form-label">Durum</label>
                        <select class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}" name="status">
                            <option value="1" @if($category->status === 1) selected @endif>Aktif</option>
                            <option value="0" @if($category->status === 0) selected @endif>Pasif</option>
                        </select>
                        @if ($errors->has('status'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('status') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="row pull-right">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- / Content -->
@endsection

resources/views/admin/category/list.blade.php
@extends('layouts.layout-without-navbar-flex')
@section('content')

    <div class="container-fluid flex-grow-1 container-p-y">

        <h4 class="font-weight-bold py-3 mb-4">
            Kategoriler
        </h4>
        <div class="row pull-right">
            <a href="{{route('categories.create',[],false)}}" class="btn btn-success"><i class="fa fa-plus-circle"></i>
                Yeni Ekle</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Başlık</th>
                    <th>Üst Kategori</th>
                    <th>Açıklama</th>
                    <th>İşlemler</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{$category->id}}</td>
                        <td>{{$category->name}}</td>
                        <td>@if($category->ancestors->count()){{$category->ancestors->pluck('name')->last()}}@else{{ '-' }}@endif</td>
                        <td>{{$category->description}}</td>
                        <td>
                            <form method="post" class="del" style="float: left;" action="{{route('categories.destroy',['id'=>$category->id],false)}}">
                                {{ method_field('DELETE') }}
                                @csrf
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>


    </div>
    <!-- / Content -->
@endsection
@section('scripts')
<script>
    $('.btn-danger').on('click',function(e){
        e.preventDefault();
        var form = $(this).parents('form');
        swal({
            title: "Emin misiniz?",
            text: "Bu işlemin geri dönüşü yoktur!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#CE4F4B",
            confirmButtonText: "Evet",
            cancelButtonText: "İptal",
            closeOnConfirm: false
        }, function(isConfirm){
            if (isConfirm) form.submit();
        });
    });
</script>
@endsection