routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(
    [
        'prefix'     => 'admin',
        'middleware' => 'check_admin',
    ],
    static function () {
        Route::resource('categories', 'Admin\CategoryController');
        Route::resource('transports', 'Admin\TransportationController');
        Route::resource('adverts', 'Admin\AdvertController');
        Route::resource('faqs', 'Admin\FaqController');
        Route::resource('advert-comments', 'Admin\AdvertCommentController');
        Route::resource('users', 'Admin\UserController');
        Route::resource('static-contents', 'Admin\StaticContentController');
        Route::resource('prices', 'Admin\PriceController');

        Route::post('upload-image', 'Admin\UploadHelperController@upload')->name('upload-image');
        Route::post('delete-image', 'Admin\UploadHelperController@delete')->name('delete-image');
        Route::post('level-1', 'Admin\DataHelperController@options')->name('options');
    }
);


Route::post('/login', 'Common\LoginController@login')->name('login');
Route::get('/admin', 'Common\LoginController@index')->name('index');

//Route::get('/data', 'Common\LoginController@getData');

app/Models/User.php
<?php

/**
 * Created by Reliese Model.
 * Date: Mon, 25 Feb 2019 12:35:16 +0000.
 */

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

/**
 * Class User
 *
 * @property int $id
 * @property string $user_id
 * @property string $type
 * @property string $name
 * @property string $avatar
 * @property string $phone
 * @property string $address
 * @property string $lokasyon
 * @property string $lat
 * @property string $lng
 * @property string $about
 * @property string $tc_id
 * @property string $email
 * @property \Carbon\Carbon $email_verified_at
 * @property string $password
 * @property string $remember_token
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @property \Illuminate\Database\Eloquent\Collection $adverts
 * @property \Illuminate\Database\Eloquent\Collection $ratings
 *
 * @package App\Models
 */
class User extends Authenticatable
{
    use HasApiTokens, Notifiable, HasRoles;

    protected $dates = [
        'email_verified_at'
    ];

    protected $hidden = [
        'password',
        'remember_token'
    ];

    protected $fillable = [
        'user_id',
        'type',
        'name',
        'avatar',
        'phone',
        'address',
        'location',
        'lat',
        'lng',
        'about',
        'tc_id',
        'email',
        'email_verified_at',
        'password',
        'remember_token'
    ];

    public function adverts()
    {
        return $this->belongsToMany(\App\Models\Advert::class);
    }

    public function advertComments()
    {
        return $this->hasMany(\App\Models\AdvertComment::class);
    }

    public function ratings()
    {
        return $this->hasMany(\App\Models\Rating::class);
    }

    public function setting()
    {
        return $this->hasOne(UserSetting::class);
    }

    public function conversations()
    {
        // todo : buraya bakılacak
        return $this->hasMany(Conversation::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function index()
    {

        $users = app(User::class)->orderBy('name')->paginate(20);

        return view('admin.user.list', compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $res = $this->api('users', 'POST', $request->all());

        dd($res);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $res  = $this->api('users/' . $id);
        $user = json_decode($res->getContent())->data;

        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $res = $this->api('users/' . $id, 'PUT', $request->all());

        dd($res);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $res = $this->api('users/' . $id, 'DELETE');


        $data = json_decode($res->getContent());

        if ($data->status) {
            return redirect()->route('users.index')->with(['success' => true]);
        }
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = app(User::class)->orderBy('created_at', 'desc')->paginate(20);
        return response()->json(['status' => 'success', 'data' => $data]);
    }

    /**
     * Show User
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        try {
            $data = app(User::class)->findOrFail($id);
        } catch (ModelNotFoundException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success', 'data' => $data]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function store(Request $request)
    {
        try {
            app(User::class)
                ->create($request->all());
        } catch (QueryException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success'], 201);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return array
     */
    public function update(Request $request, $id)
    {
        try {
            $data = app(User::class)->findOrFail($id);
            $data->update($request->all());
        } catch (QueryException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        } catch (ModelNotFoundException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array
     */
    public function destroy($id)
    {
        try {
            $data = app(User::class)->findorFail($id);
            $data->delete();
        } catch (ModelNotFoundException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }

        return response()->json(['status' => 'success']);
    }
}

resources/views/admin/user/edit.blade.php
{{dd($faq)}}

resources/views/admin/user/list.blade.php
@extends('layouts.layout-without-navbar-flex')
@section('content')

    <div class="container-fluid flex-grow-1 container-p-y">

        <h4 class="font-weight-bold py-3 mb-4">
            Kullanıcılar
        </h4>
        <div class="row pull-right">
            <a href="{{route('categories.create',[],false)}}" class="btn btn-success"><i class="fa fa-plus-circle"></i>
                Yeni Ekle</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Kullanıcı Türü</th>
                    <th>Adı Soyadı</th>
                    <th>Telefon</th>
                    <th>Email</th>
                    <th>Adres</th>
                    <th>İşlemler</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{$user->type}}</td>
                        <td>{{$user->name}}</td>
                        <td>{{$user->phone}}</td>
                        <td>{{$user->email}}</td>
                        <td>{{$user->address}}</td>
                        <td>
                            <a href="{{route('users.edit',['id'=> $user->id],false)}}"
                               class="btn btn-xs btn-primary" style="margin-left: 5px"><i class="fa fa-info-circle"></i></a>
                            <form method="post" class="del" style="float: left;" action="{{route('users.destroy',['id'=>$user->id],false)}}">
                                {{ method_field('DELETE') }}
                                @csrf
                                <button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $users->links() }}
        </div>


    </div>
    <!-- / Content -->
@endsection
@section('scripts')
    <script>
        $('.btn-danger').on('click',function(e){
            e.preventDefault();
            var form = $(this).parents('form');
            swal({
                title: "Emin misiniz?",
                text: "Bu işlemin geri dönüşü yoktur!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#CE4F4B",
                confirmButtonText: "Evet",
                cancelButtonText: "İptal",
                closeOnConfirm: false
            }, function(isConfirm){
                if (isConfirm) form.submit();
            });
        });
    </script>
@endsection